var keepValue = true

startingMessage = 'Welcome to GenGPT, where your images open the door to personalized, insightful responses tailored just for you.'
startingPrompt = `Write a single-line welcome message to a user of GenGPT which produces responses based on the user's images. THE MESSAGE SHOULD INCLUDE "GenGPT". NO QUOTES PLEASE. DO NOT TALK ABOUT THE FUTURE or DISCOVERY. Please add a new line followed by " - This message was generated by AI." as well.`